In [2]:
import torch
from torch.utils.data import Dataset, DataLoader

# サンプルデータセットの作成
class SampleDataset(Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

# データとラベルの定義
data = torch.arange(10)
labels1 = torch.arange(10)
labels2 = torch.arange(9, -1, -1)  # ラベルを反転

# シード値を設定してデータローダを作成
torch.manual_seed(100)
dataset1 = SampleDataset(data, labels1)
dataloader1 = DataLoader(dataset1, batch_size=1, shuffle=True)

torch.manual_seed(100)
dataset2 = SampleDataset(data, labels2)
dataloader2 = DataLoader(dataset2, batch_size=1, shuffle=True)

# シャッフルされたデータの順序を確認
print("Shuffled order with labels1:")
for batch in dataloader1:
    print(batch)

print("\nShuffled order with labels2:")
for batch in dataloader2:
    print(batch)


Shuffled order with labels1:
[tensor([1]), tensor([1])]
[tensor([6]), tensor([6])]
[tensor([5]), tensor([5])]
[tensor([8]), tensor([8])]
[tensor([3]), tensor([3])]
[tensor([4]), tensor([4])]
[tensor([2]), tensor([2])]
[tensor([0]), tensor([0])]
[tensor([7]), tensor([7])]
[tensor([9]), tensor([9])]

Shuffled order with labels2:
[tensor([3]), tensor([6])]
[tensor([1]), tensor([8])]
[tensor([0]), tensor([9])]
[tensor([5]), tensor([4])]
[tensor([4]), tensor([5])]
[tensor([6]), tensor([3])]
[tensor([8]), tensor([1])]
[tensor([9]), tensor([0])]
[tensor([2]), tensor([7])]
[tensor([7]), tensor([2])]


In [ ]:
import torch

# シード値を設定
torch.manual_seed(42)

# ランダムテンソルを生成
random_tensor = torch.randn(3, 3)
print(random_tensor)

# 再度シード値を設定して同じ乱数を生成
torch.manual_seed(42)
same_random_tensor = torch.randn(3, 3)
print(same_random_tensor)

# 異なるシード値を設定すると異なる乱数が生成される
torch.manual_seed(42)
different_random_tensor = torch.randn(3, 3)
print(different_random_tensor)


In [2]:
import torch

In [11]:
for i in range(3):
	torch.manual_seed(0)
	print(torch.rand(3))
	torch.manual_seed(0)
	print(torch.rand(4))

tensor([0.4963, 0.7682, 0.0885])
tensor([0.4963, 0.7682, 0.0885, 0.1320])
tensor([0.4963, 0.7682, 0.0885])
tensor([0.4963, 0.7682, 0.0885, 0.1320])
tensor([0.4963, 0.7682, 0.0885])
tensor([0.4963, 0.7682, 0.0885, 0.1320])
